AWSTemplateFormatVersion: '2010-09-09'
Description: Creaci칩n de una instancia EC2 b치sica sin par치metros

Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      KeyName: vockey 
      ImageId: ami-007868005aea67c54 # Amazon Linux 2 AMI en la regi칩n us-east-1
